### ISSUE TITLE
Group game's are labeled experiences and have the default website style

### ISSUE THREAD

**Issue by ghost** [sayorisocks/robsblocks#10]
![Screenshot_1520](https://github.com/sayorisocks/robsblocks/assets/79523801/d1e86556-a05f-4fdc-9229-f46909c6251d)
Settings:
![Screenshot_1521](https://github.com/sayorisocks/robsblocks/assets/79523801/86c321f4-0cc3-4a78-b793-7c4f28aa11f6)

**Comment by tsukinousako** [comment]
try updating, that has been fixed for a while
