### ISSUE TITLE
game page screwed up for all themes

### ISSUE THREAD

**Issue by Spoonus** [sayorisocks/robsblocks#11]
![uh 1](https://github.com/sayorisocks/robsblocks/assets/167826701/84eea237-dac8-49ea-b07e-facaea6e3a1d)
![uh 2](https://github.com/sayorisocks/robsblocks/assets/167826701/12675b65-3fff-48ca-a940-6a4243a0ef63)
![uh 3](https://github.com/sayorisocks/robsblocks/assets/167826701/5e6e82df-8e96-4c6a-a3b9-5a272c73ac73)
yeah i don't know what happened but it just stopped working properly???

**Comment by junnlives** [comment]
+1, had this issue aswell on 1.1.7, updated to 1.1.8 and now it's even worse even with only btroblox
![image](https://github.com/sayorisocks/robsblocks/assets/69032098/edfaa39e-0f53-45d0-9122-1e8d0684c1af)

**Comment by fartfacebill61** [comment]
i am on 1.0.6 and i have the same problem + the build and robux buttons are invisible

**Comment by tsukinousako** [comment]
the games page should be fixed now, roblox made some weird layout changes, sorry!!!
