### ISSUE TITLE
a few problems i have encountered

### ISSUE THREAD

**Issue by fartfacebill61** [sayorisocks/robsblocks#12]
theres only 2 bugs that i have noticed. firstly the ROBUX button has been placed next to the build button. both buttons are invisible and, from the jan 2014 version onwards they are not even in line with the top banner. secondly, the active players, time created, visits, gear allowed etc have been moved from under the play button to under the description, and the font and sizing is wrong. update: i changed to 1.1.8 and although build and robux are back, the game page seems to have gotten worse!
![build and robux button invisible](https://github.com/sayorisocks/robsblocks/assets/167017980/207804e2-705a-401e-acac-ca461636296f)

**Comment by tsukinousako** [comment]
refer to https://github.com/sayorisocks/robsblocks/issues/11#issuecomment-2087347753
