### ISSUE TITLE
game stats broke YET AGAIN

### ISSUE THREAD

**Issue by Spoonus** [sayorisocks/robsblocks#17]
![uh what the hell](https://github.com/sayorisocks/robsblocks/assets/167826701/57b25041-1a96-4d2c-b784-4f2a13a085d1)
why does this keep on happening

**Comment by sharkievaded** [comment]
same thing for me!

**Comment by sayorisocks** [comment]
not happening on my end; share what browser ur using

**Comment by tsukinousako** [comment]
should be fixed now
