### ISSUE TITLE
Roblox Logo is just blank

### ISSUE THREAD

**Issue by ZiggyCastillo** [sayorisocks/robsblocks#19]
Same as in title, ROblox logo is just blank, sometimes it will appear for 00000.1 secs and very transparent and then immediatly go back to the white block
![image](https://github.com/sayorisocks/robsblocks/assets/156471721/2136a8df-f92e-4ea0-a3a6-f96ead6931c6)

**Comment by tsukinousako** [comment]
this is likely an issue on your end, logo appears fine for me
![firefox_dRMbjSvoSg](https://github.com/sayorisocks/robsblocks/assets/34829888/02b3aa2e-b332-402c-94b4-8cd0b8d9bdd6)
