### ISSUE TITLE
2014-esque theme home page being completely misaligned ever since the removal of user ads

### ISSUE THREAD

**Issue by SammyGoesHowdy** [sayorisocks/robsblocks#24]
As the title says, ever since the removal of user ads, most style options here (aside from december 2014) has a completely broken home page (image below is december 2013, in dark mode) ![image](https://github.com/sayorisocks/robsblocks/assets/105883916/ae44a3d1-5cf8-43b3-ac72-c20c3df17df2)

As you can see, December 2014 is fine.
![image](https://github.com/sayorisocks/robsblocks/assets/105883916/eeb33b24-2f21-4aa4-b98e-9b0f7c807290)

It also doesn't matter if its light mode or dark mode, its always going to be like that.

**Comment by SammyGoesHowdy** [comment]
UPDATE: These screenshots were took with 1.2.2, but I've updated to 1.4.4 and alas, still broken.

**Comment by SammyGoesHowdy** [comment]
ANOTHER UPDATE: It actually.. got worse?
![image](https://github.com/sayorisocks/robsblocks/assets/105883916/c33d5b02-93fb-4a83-8b10-ee6a9957ba1b)

**Comment by SammyGoesHowdy** [comment]
December 2014 is fine though, I think. I am very confused.
![image](https://github.com/sayorisocks/robsblocks/assets/105883916/1b8194b8-7b3b-4da1-9ead-844e9201eda9)

**Comment by tsukinousako** [comment]
this is probably because something you have is removing the recommended games & today’s picks section from the home page

**Comment by SammyGoesHowdy** [comment]
yep, that was the case. my bad. case closed!
