### ISSUE TITLE
What happened to the homepage?

### ISSUE THREAD

**Issue by fartfacebill61** [sayorisocks/robsblocks#27]
the homepage looks really strange. Loads of text is overlapping and the pictures are super small. some text comes out of its 'box' and it looks quite messy. I really hope this gets updated soon.

![Screenshot 2024-06-23 173736](https://github.com/sayorisocks/robsblocks/assets/167017980/33d3893d-3771-4256-94a8-c54b1ec01f40)

ALSO the font looks WAY different than what it used to be. It's much more rounded and smooth, and sometimes capitalized in random places. Is this an update or a bug? It looks more like 'modern' roblox.
I might be nitpicking some of it now but i really can't tell if it's a bug.

I am on librewolf (firefox) if that has anything to do with it.

**Comment by tsukinousako** [comment]
try clearing your browser cache? the homepage should not be looking like that at all

**Comment by segashiro** [comment]
What extensions do you have on?

**Comment by fartfacebill61** [comment]
Ill Turn off ropro and see if that makes a difference

**Comment by fartfacebill61** [comment]
It isn't RoPro that's causing the problem. It's still super broken. It's not a Firefox thing either because the same happens on brave. Sadly I can't check Microsoft edge as I am unable to update the userscript. I've tried the basics like zooming in and out, but that doesn't work. One more thing - The december 2014 style is completely broken by RoPro. Everything overlaps and it is either too big or too small, and it all disappears.

**Comment by fartfacebill61** [comment]
oops

**Comment by tsukinousako** [comment]
..try clearing your browser cache

**Comment by fartfacebill61** [comment]
how do you do that on librewolf 😭😭😭

**Comment by TheMaker69420** [comment]
librewolf is literally just firefox you can probably delete it the same way you can on firefox lmao

**Comment by fartfacebill61** [comment]
it's okay an update while back fixed it
