### ISSUE TITLE
alteast do 2014 july header,

### ISSUE THREAD

**Issue by asfasdfasdfsdsdf** [sayorisocks/robsblocks#3]
https://web.archive.org/web/20140731082137/http://www.roblox.com/catalog/

Do something like this (also make leaderboard button not work, because it doesn't exist anymore)

also 2014 july header is similar to the main header in CSS

Just do it please, and this is a request

**Comment by tsukinousako** [comment]
late 2013 and july 2014 are identical ; no plans for either of them sorry
