### ISSUE TITLE
Report Abuse page is not changed for Dark Theme

### ISSUE THREAD

**Issue by Greenbulb** [sayorisocks/robsblocks#31]
Images below showing it using White text on White background.

![zejejw8i](https://github.com/sayorisocks/robsblocks/assets/62176500/ae33407e-c857-4c25-a32c-0e3e6e71e261)
![0rnk65d7](https://github.com/sayorisocks/robsblocks/assets/62176500/84e1dde6-d641-482d-b79c-e7bb4807a1d8)

**Comment by tsukinousako** [comment]
this has been fixed now, thank you!
