### ISSUE TITLE
Friends list goes across the home page, instead of down the side.

### ISSUE THREAD

**Issue by Mantah18** [sayorisocks/robsblocks#44]
Friends list goes across the home page, instead of the way as intended (down the side). Chat/Join button for a user is also the current 2024 one.

![Screenshot 2024-09-13 125703](https://github.com/user-attachments/assets/5e39381b-ddcf-428f-9486-516a42510b27)

**Comment by Spoonus** [comment]
![uhhh](https://github.com/user-attachments/assets/b6a087a2-f9c5-4a2d-8833-cd99181f64fe)
comin here to say i have the same problem

**Comment by tsukinousako** [comment]
should be fixed now, thank you!
