### ISSUE TITLE
Friends list goes down the side of the home page, instead of across. (Dec 2014 & 2015)

### ISSUE THREAD

**Issue by rendan-n** [sayorisocks/robsblocks#48]
title. addons enabled that affect the page are ublock origin and btroblox, i also have tampermonkey but disabled the scripts for this
![Screenshot 2024-10-21 193047](https://github.com/user-attachments/assets/f0fbe983-0417-4d87-852a-76c52ada753f)
![Screenshot 2024-10-21 193155](https://github.com/user-attachments/assets/fbee2936-d319-463d-bd95-e5e29ade520d)
![Screenshot 2024-10-21 193208](https://github.com/user-attachments/assets/e243bdda-f776-4a4c-9f52-9fde83c060f8)

**Comment by tsukinousako** [comment]
should be fixed now, ty!
