### ISSUE TITLE
homepage got broken again

### ISSUE THREAD

**Issue by L48YR1NTH** [sayorisocks/robsblocks#49]
<img width="1650" alt="Screenshot 2024-10-28 at 9 10 43 PM" src="https://github.com/user-attachments/assets/4a1077b1-6163-467e-ac73-e8a1f38ab26d">
tried updating and re-downloading and turning off all my other extensions and no results :P DARN YOU ROBLOX!!!

**Comment by goodoldweb2013** [comment]
which script are you using for the avatar and greetings? do you have legacy site restoration?

**Comment by L48YR1NTH** [comment]
roqol, but the issue persists even after disabling it. whats legacy site restoration?

**Comment by goodoldweb2013** [comment]
> roqol, but the issue persists even after disabling it. whats legacy site restoration?

where can i install roqol? because legacy site restoration breaks too

**Comment by goodoldweb2013** [comment]
> roqol, but the issue persists even after disabling it. whats legacy site restoration?

try disabling it. also, what's the settings fo roqol to enable homepage greetings?

**Comment by L48YR1NTH** [comment]
qol settings>home>home welcome header. along with a little extra customization underneath the toggle. i have disabled it, i think the issue is with this specific userstyle. changing the theme date doesn't do anything, and none of my other roblox extensions are the cause. i've turned all of them off, both as a group and individually, to no results

**Comment by tsukinousako** [comment]
what ver is this?

**Comment by goodoldweb2013** [comment]
> what ver is this?

I'm actually doing a script for this extension to be compatible with your script. my "tweaks" scripts doesn't use "legacy site restoration" for the avatar and greetings on home, i switched to the extension mentioned (Roqol).

**Comment by L48YR1NTH** [comment]
i'm on version 1.5.4, stylus says up to date

**Comment by goodoldweb2013** [comment]
> i'm on version 1.5.4, stylus says up to date

Outdated, please, manually update the script on userstyles.world

**Comment by L48YR1NTH** [comment]
Ah, i thought that's what the issue mightve been. not sure why stylus was giving me the wrong version. thanks!
