### ISSUE TITLE
fix alignment of forum disabled page

### ISSUE THREAD

**Issue by j4wassup** [sayorisocks/robsblocks#5]
https://www.roblox.com/forum-disabled-page
![image](https://user-images.githubusercontent.com/99167692/223006945-2a5013cb-b9ca-4bb5-8d05-a5510035d855.png)
self explanatory, this is not because of the late 2013 header, as proven by this 2nd screenshot
![image](https://user-images.githubusercontent.com/99167692/223007075-09ce2d2a-522a-4a59-9b62-d98ef2bf2619.png)
you should also change the font and other stuff

**Comment by tsukinousako** [comment]
why
