### ISSUE TITLE
friends list on june 2013 oddity

### ISSUE THREAD

**Issue by cottonable** [sayorisocks/robsblocks#52]
![image](https://github.com/user-attachments/assets/d4c7b6d8-119d-4462-8269-4413d918241a)
robox

**Comment by tsukinousako** [comment]
what ver is this?

**Comment by cottonable** [comment]
june 2013, downloaded from userstyles.world

**Comment by tsukinousako** [comment]
no what version of the theme is this

**Comment by cottonable** [comment]
1.6.5.1

**Comment by tsukinousako** [comment]
should be fixed now, reply if this keeps happening, ty!

**Comment by cottonable** [comment]
![image](https://github.com/user-attachments/assets/fea25384-241d-469c-93df-3fdf1cc1b88f)
semi-fixed... border doesn't extend :(
