### ISSUE TITLE
2 Bugs: Today's Picks clips into Continue, Play Button is kind of duplicated with part of it under the actual play button.

### ISSUE THREAD

**Issue by Mantah18** [sayorisocks/robsblocks#56]
![Screenshot 2024-12-08 123015](https://github.com/user-attachments/assets/a738fdb0-e45d-49db-9c96-2f06658c9a70)
![Screenshot 2024-12-08 123054](https://github.com/user-attachments/assets/4ff38d72-84ce-4184-9775-749c71803057)

Play Button has other part of button below it, not clickable.
"Today's Picks" clips into "Continue" Part of Home Page

June 2013 Website Style

**Comment by tsukinousako** [comment]
https://github.com/sayorisocks/robsblocks/issues/55#issuecomment-2518625117
