### ISSUE TITLE
Profile, Friends, Inventory, Messages, Groups, Home, Money, and Avatar not themed in the 2010 style

### ISSUE THREAD

**Issue by gazecube** [sayorisocks/robsblocks#6]
I'm trying out the 2010 style, it's very nice, but there's ALOT missing. Everything mentioned in the title, and possibly more aren't skinned. I really hope to see this fully fleshed out one day, cause the layout is the most accurate 2010 layout I've ever seen.

**Comment by tsukinousako** [comment]
maybe..
