### ISSUE TITLE
(2014) Weird Margin Issues?

### ISSUE THREAD

**Issue by sehvie** [sayorisocks/robsblocks#9]
Big fan of the style so far, however there are some issues with the page margins on certain tabs. (Details in attached images.)
I used December 2013 for the screenshots, but the issues are consistent on every option.
![firefox_LEC47ZO6MN](https://github.com/sayorisocks/robsblocks/assets/111326521/4d9d831e-3981-4170-aea5-45ee59ce7057)
![firefox_cysyYrGh8d](https://github.com/sayorisocks/robsblocks/assets/111326521/efd2641f-56d9-4424-a0ff-89dd59134d6b)

**Comment by sehvie** [comment]
obviously, stuff like this kinda kills the whole point of the theme lol
![image](https://github.com/sayorisocks/robsblocks/assets/111326521/55964ac2-7a08-47db-b072-7fcb00c080ee)

**Comment by tsukinousako** [comment]
hi!
if u turn on _btroblox's **hide ads**_ option there should be less extra space now!!
also fixed the . unaligned stuff too (( except for the sponsored tab bc i never see that onsite lool ))

thank u for the feedback :)

![firefox_Nf9MQJG0EY](https://github.com/sayorisocks/robsblocks/assets/34829888/4c288c76-8be4-4b37-b342-6372210b51d0)
![firefox_QwJpcNlFNF](https://github.com/sayorisocks/robsblocks/assets/34829888/181745a1-a721-4d95-a97f-7fa80a389886)
![firefox_GpL4dcWut4](https://github.com/sayorisocks/robsblocks/assets/34829888/b851722a-85e2-4e66-8146-26489cef06d1)
